version: '3.7'

services:
  redis:
    image: redis:4
  wxmini:
    build: ./php
    image: phpfpm:1
    volumes:
      - '${WXMINI_APP}:/www/wxmini'
    ports:
      - "9000:9001"
    links:
      - 'redis'
